# use the oficial python 3.11 image as base image
FROM python:3.11

# Set the working directory to /app
WORKDIR /app

# Update package list and Install neccesary build materials 
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl \ 
    bash \
    && rm -rf /var/lib/apt/lists/*

# Install poetry 
RUN curl -sSL https://install.python-poetry.org | python3 -

# Copy pyproject.toml and poetry.lock 
COPY pyproject.toml poetry.lock ./

# Add poetry to path
ENV PATH="/root/.local/bin:$PATH"

# Copy the rest of the source code into the container
COPY . .

# Install dependencies
RUN poetry install 

# Make the prestart.sh script executable
RUN chmod +x ./prestart.sh

# Expose the port the application runs on
EXPOSE 8000

# Command to run the executable and start the server
CMD ["sh", "-c", "poetry run bash ./prestart.sh && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
